- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: copy nginx config
  copy:
    src: default.conf
    dest: /etc/nginx/sites-available/default
  notify: reload nginx

- name: deploy html page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: reload nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: true
